---
title: "lab 1"
author: "anisha, diana, dillon, futing, ian"
date: "3/29/2022"
output: html_document
---

# Getting Started
```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)

set.seed(123) 

m <- lm(mpg ~ hp + cyl + drat, mtcars)

l <- list(a = list(m = matrix(1:12, ncol = 3),
                   v = 1:7),
          b = data.frame(student = 1:15,
                         score = rnorm(15, 100, 10)))
```


#1
```{r, echo = FALSE, warning = FALSE, message = FALSE}
m$qr$tol

attributes(m$terms)$term.labels ##??

attr(attr(m$model, "terms"), "term.labels") ##method 2
```


#2

```{r, echo = FALSE, warning = FALSE, message = FALSE}
l$a$m
l[[1]][1]

# maintaining matrix structure
l$a$m[,3, drop = FALSE] 

# extract the score for student 7 in the df
l$b[7,] # method 1
l[["b"]][7, ] # method 2
```


#3
```{r, warning = FALSE, message = FALSE}
here::set_here(path='..')
insurance <- readr::read_csv(here::here("data", "insurance_coverage.csv"))

split <- split(insurance, list(insurance$age_bucket, insurance$sex_name))
```

#4
```{r, echo = FALSE, warning = FALSE, message = FALSE}
means <- rep(NA, length(split))
for(i in seq_along(split)){
  means[i] <- mean(split[[i]]$hc_pop, na.rm = TRUE)
}
means
```

#5
```{r, echo = FALSE, warning = FALSE, message = FALSE}
means2 <- unlist(lapply(split, function(x) mean(x$hc_pop, na.rm = TRUE)))
means2

means3 <- sapply(split, function(df) mean(df$hc_pop, na.rm = TRUE))
means3

means4 <- vapply(split, function(df) mean(df$hc_pop, na.rm = TRUE), FUN.VALUE = double(1))
means4

```

#6
```{r, echo = FALSE, warning = FALSE, message = FALSE}
plots <- lapply(split, function(x) {
  ggplot(x, aes(year, hc_pop)) +
    geom_point() +
    geom_line() +
    ylim(min(insurance$hc_pop), max(insurance$hc_pop))
    
})

```

#7
```{r, warning = FALSE, message = FALSE}
filenames <- here::here(
  "plots",
  paste0(names(split), ".png")
)

for(i in seq_along(plots)) {
    ggsave(filenames[i], # single bracket
           plots[[i]], # double bracket
           device = "png",
           width = 6.5, 
           height = 8)
}

```

