---
title: "Midterm"
author: "Anisha, Diana, Dillon, Futing, Ian"
date: "4/24/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r,  knitr::opts_chunk$set(cache = TRUE)}
library(tidyverse)


download_file <- function(year) {
  link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
  rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}

raw_dat <- map_dfr(list(15, 16, 17, 18), ~download_file(.x))

cleaned_dat <- raw_dat %>% 
  janitor::clean_names() %>% 
  filter(., 
         student_group == "White" | 
           student_group == "Hispanic/Latino") %>% 
  select(academic_year, district, school, student_group, grade_level, 
         starts_with("number_level")) %>% 
  pivot_longer(starts_with("number_level"), names_to = "level", 
               names_prefix = "number_level_", values_to = "n", 
               values_drop_na = TRUE)
rm(raw_dat)
```

```{r Part A2}


count2 <- cleaned_dat %>% 
  nest_by(district) %>% 
  rowwise() %>% 
  mutate(unique = count(unique(data[2]))) %>% 
  unnest(data) %>% 
  nest_by(district, academic_year, student_group, level) %>% 
  rowwise() %>% mutate(sum = sum(data[3])) %>% 
  unnest(data) %>% 
  nest_by(district, academic_year, unique, student_group, level, sum) %>% 
  select(-data) %>% 
  pivot_wider(names_from = student_group, values_from = sum) %>% 
  filter(!is.na(`White`)) 


count2 <- count2 %>% 
  filter(!is.na(count2$`Hispanic/Latino`)) 


```

```{r Part B1}

# remotes::install_github("datalorax/gapr")
library(gapr)
library(purrr)


v1 <- count2 %>%
  group_by(district) %>%
  nest() %>%
  mutate(v_diff = map(data, ~estimate_v(data = .x, "White","Hispanic/Latino"))) %>%
  unnest(v_diff)


v2 <- count2 %>%
  nest_by(district) %>%
  rowwise() %>%
  summarize(v_diff = list(estimate_v(data = data, "White","Hispanic/Latino"))) %>%
  unnest(v_diff)

```

```{r Part B2}
# plot
v <- data.frame(v2$v, v1$v)

ggplot(v, aes(x = v2.v, y = v1.v,)) +
  geom_point(color = "steelblue1") +
  geom_line(color = "steelblue1") +
  theme_dark()
```

```{r Part B3}
library(glue)
library(ggtext)

# calculate achievement difference by district & year
v3 <- count2 %>%
  group_by(district, academic_year) %>%
  nest() %>%
  mutate(v_diff = map(data, ~estimate_v(data = .x, "White","Hispanic/Latino"))) %>%
  unnest(v_diff)

# select values for plots
selectVals <- v3 %>%
  mutate(n_school = data[[1]]$unique[1,1]) %>%
  select(district, n_school, academic_year, v, v_se)

#select first 100 districts
dists <- unique(selectVals$district)[1:100] 
firstHundred <- selectVals %>% 
  filter(district %in% dists)

# nest by district
by_district <- firstHundred %>%
    group_by(district) %>%
    nest()

# version 1
version1 <- by_district %>%
    mutate(plots1 = map(data, y=district, ~{
      ggplot(data = .x, aes(academic_year, v)) +
        geom_point(aes(colour = cut(v, c(-Inf, 0, Inf))), show.legend = FALSE) +
        scale_color_manual(name = "v", values = c("(-Inf,0]" = "mediumorchid2", "(0,Inf]" = "blue")) +
        geom_errorbar(aes(ymin=v-v_se, ymax=v+v_se), width = 0.2, color = 'gray50') +
        geom_line(aes(group=1), color = 'gray50') +
        labs(x = 'School year',
             y = 'Average achievement difference (SD units)',
             title = glue("Achievement Gap Estimates: {.y}"),
             subtitle = "Negative values indicate <span style='color: #BC4EE5'>White</span> students have higher average achievement<br/>Positive values indicate <span style='color: #4E5FEB'>Hispanic/Latino</span> students have higher achievement",
             caption = paste('Note: District included', .x[[1]][[1]], 'schools')) +
        geom_hline(yintercept= 0, color = 'red') +
        theme_minimal() +
        theme(plot.subtitle = element_markdown(),
              plot.title.position = "plot")
      }))

# version 2
version2 <- firstHundred %>%
  ungroup() %>%
  nest_by(district) %>%
  mutate(
    plots2 = list(
      ggplot(data, aes(academic_year, v)) +
        geom_point(aes(colour = cut(v, c(-Inf, 0,Inf))), show.legend = FALSE) +
        scale_color_manual(name = "v", values = c("(-Inf,0]" = "mediumorchid2","(0,Inf]" = "cornflowerblue")) +
        geom_errorbar(aes(ymin=v-v_se, ymax=v+v_se), width = 0.2, color = 'gray50') +
        geom_line(aes(group=1), color = 'gray50') +
        labs(x = 'School year',
             y = 'Average achievement difference (SD units)',
             title = glue("Achievement Gap Estimates: {district}"),
             subtitle = "Negative values indicate <span style='color: #BC4EE5;'>White</span> students have higher average achievement<br/>Positive values indicate <span style='color: #4E5FEB;'>Hispanic/Latino</span> students have higher achievement",
             caption = paste('Note: District included', {data[[1]][[1]]}, 'schools')) +
        geom_hline(yintercept= 0, color = 'red') +
        theme_minimal() +
        theme(plot.subtitle = element_markdown(),
              plot.title.position = "plot")
    )
  )



```

```{r bonus}
library(patchwork)
bonus <- map2(version1$plots1, version2$plots2, `+`)
# bonus[[1]]
```


```{r Part B4, warning=FALSE}
fs::dir_create(here::here("plots"))
files <- map_chr(
  str_replace_all(
    tolower(version1$district), " ", "_"), 1)
paths <- here::here("plots", glue("achievement-gap_{files}.png"))
version1 %>%
  ungroup() %>%
  mutate(path = paths) %>%
  rowwise() %>%
  summarize(
    ggsave(
      path,
      plots1,
      width = 9,
      height = 6)
  )
```




