---
title: "The Personality Structures of the 50 States"
author: "Anisha Babu, Diana DeWald, Ian Shryock, Dillon Welindt, Futing Zou"
output: 
  bookdown::pdf_document2:
    toc: TRUE
    lof: TRUE
    lot: TRUE
    extra_dependencies: ["tocbibind"]
always_allow_html: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(dataverse)

# download data from files
# SAPA <- read.csv('sapaTempData04apr2006thru18aug2010.csv')
load('IPIPitemLists.rdata')

# download data from url
Sys.setenv("DATAVERSE_SERVER" = "dataverse.harvard.edu")
SAPA <- get_dataframe_by_name(
  "sapaTempData04apr2006thru18aug2010.tab",
  "10.7910/DVN/H9RQD6")

```

```{r preprocessing}
SAPA <- SAPA %>%
  # filter in US
  filter(country == "USA") %>%
  # filter 50 states
  filter(!state %in% c('District of Columbia', 'Guam', 'Palau','Puerto Rico', 'Virgin Islands',
                       'Northern Mariana Islands', 'American Samoa', 'Marshall Islands', NA)) 

# filter out rows with all NA
SAPA <- SAPA[rowSums(is.na(SAPA)) < 99, ]

# combine all 150 IPIP Q's 
IPIPkeys <- c()
for (i in IPIPitemLists) {IPIPkeys <- append(IPIPkeys, i)}
# select only Q's in dataset
matchKeys <- match(colnames(SAPA), IPIPkeys) %>%
  na.omit()
IPIPkeys <- IPIPkeys[matchKeys]

```

\renewcommand{\thetable}{S\arabic{table}} 
\renewcommand{\thefigure}{S\arabic{figure}}



\definecolor{fancyTextColor}{HTML}{4284f5}
\definecolor{hightlightColor}{HTML}{FFFF66}

\newpage

\listoftables

\newpage

\listoffigures

\newpage



