---
title: "Lab 2"
author: "Anisha, Diana, Dillon, Futing, Ian"
date: "4/11/2022"
output: html_document
---
# Setup
```{r, echo  = FALSE}
file <- "https://github.com/datalorax/esvis/raw/master/data/benchmarks.rda"
load(url(file))
head(benchmarks)

library(tidyverse)

benchmarks <- benchmarks %>%
	as_tibble() %>%
	mutate(wave = case_when(season == "Fall" ~ 0,
	                        season == "Winter" ~ 1,
	                        TRUE ~ 2))
```


```{r, echo  = FALSE}
by_id <- split(benchmarks, benchmarks$sid)



models <- map(by_id, ~lm(math~wave, data = .x))
coefs <- map(models, coef)
slope <- map_dbl(coefs, 2)
int <- map_dbl(coefs, 1)

to_plot <- cbind(slope, int) %>% 
  na.omit() %>% 
  data.frame


ggplot(benchmarks, aes(wave, math)) +
  geom_abline(
    aes(intercept = int, 
        slope = slope), 
    size = 0.01, 
    data = to_plot
  ) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    color = "magenta",
    size = 2
  ) +
  scale_x_continuous(
    limits = c(0, 2),
    breaks = 0:2,
    labels = c("Fall", "Winter", "Spring")
  ) +
  scale_y_continuous(
    limits = c(115, 300)
  )

```

# Part B
```{r}
install.packages("repurrrsive")
library(repurrrsive)
```
```{r}
#unique(map_chr(sw_species, ~.x$hair_colors))
species_hair <- tibble(species = map_chr(sw_species, ~.x$name),
                       hair_color = map_chr(sw_species, ~.x$hair_colors)) %>%
  filter(hair_color != "n/a" & 
           hair_color != "none" & 
           hair_color != "unknown")

species_hair
```




#Part C
```{r}
##Part 1
library(httr)
ability1 <- GET("https://pokeapi.co/api/v2/ability/1") %>%
	content("parsed") 

abilities_n <- 5
abilities_list <- 1:abilities_n %>% map(~GET(paste0("https://pokeapi.co/api/v2/ability/", .x)) %>%
	content("parsed"))
```

```{r}
abilities_df <- abilities_list %>% map_df(~tibble(name =.x$name, ability = list(.x), pokemonNumber = length(.x$pokemon)))
abilities_df


```

