---
title: "The Personality Structures of the 50 States"
author: "Anisha Babu, Diana DeWald, Ian Shryock, Dillon Welindt, Futing Zou"
output: 
  bookdown::pdf_document2:
    toc: TRUE
    lof: TRUE
    lot: TRUE
    extra_dependencies: ["tocbibind"]
always_allow_html: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(dataverse)
library(kableExtra)
library(psych)

# download data from url
Sys.setenv("DATAVERSE_SERVER" = "dataverse.harvard.edu")
SAPA <- get_dataframe_by_name(
  "sapaTempData04apr2006thru18aug2010.tab",
  "10.7910/DVN/H9RQD6")

# IPIP keys list
IPIPkeysList <- list(
IPIP100agreeableness = c("-q_140", "-q_146", "q_150", "-q_195", "-q_200", "q_217", "-q_838", "q_844", "q_1041", "q_1053", "q_1162", "-q_1163", "q_1206", "q_1364", "q_1385", "q_1419", "q_1705", "q_1763", "q_1792", "q_1832"),
IPIP100conscientiousness = c("q_76", "q_124", "q_530", "q_619", "-q_626", "-q_904", "q_931", "q_962", "-q_1254", "-q_1255", "q_1290", "q_1333", "q_1374", "-q_1397", "q_1422", "-q_1452", "-q_1483", "q_1507", "-q_1696", "-q_1949"),
IPIP100extraversion = c("-q_241", "q_254", "q_262", "-q_403", "-q_690", "q_698", "-q_712", "q_815", "q_819", "-q_901", "-q_1114", "-q_1180", "q_1205", "q_1410", "-q_1480", "q_1742", "q_1768", "q_1803", "-q_1913"),
IPIP100intellect = c("q_128", "q_132", "-q_194", "q_240", "-q_316", "q_422", "q_492", "q_493", "-q_609", "q_1050", "q_1058", "-q_1083", "-q_1088", "q_1090", "q_1388", "q_1392", "q_1738", "-q_1861", "q_1893", "-q_1964"),
IPIP100stability = c("-q_108", "q_177", "q_248", "-q_497", "-q_890", "-q_952", "-q_960", "-q_974", "-q_979", "-q_986", "-q_995", "-q_1020", "-q_1099", "-q_1479", "-q_1505", "q_1585", "q_1677", "q_1683", "-q_1775", "-q_1989"),
IPIP50agreeableness = c("q_844", "q_1792", "q_1763", "q_150", "q_1419", "q_1053", "-q_838", "-q_200", "-q_195", "-q_1163"),
IPIP50conscientiousness = c("-q_1255", "-q_1397", "-q_1483", "-q_1696", "q_124", "q_1290", "q_1507", "q_76", "q_931", "q_962"),
IPIP50extraversion = c("q_819", "q_698", "q_262", "q_1803", "q_1742", "-q_712", "-q_690", "-q_241", "-q_1180", "-q_1114"),
IPIP50intellect = c("q_128", "q_240", "q_1893", "q_1738", "q_1090", "q_1058", "q_1050", "-q_609", "-q_194", "-q_1088"),
IPIP50stability = c("-q_108", "-q_1099", "-q_1479", "-q_1989", "-q_497", "-q_974", "-q_986", "-q_995", "q_1677", "q_248")
)

```

```{r preprocessing}
SAPA <- SAPA %>%
  # filter in US
  filter(country == "USA") %>%
  # filter 50 states
  filter(!state %in% c('District of Columbia', 'Guam', 'Palau','Puerto Rico', 'Virgin Islands',
                       'Northern Mariana Islands', 'American Samoa', 'Marshall Islands', NA)) 

# filter out rows with all NA
SAPA <- SAPA[rowSums(is.na(SAPA)) < 99, ]

# in list form select only used Q's
usedQ <- colnames(SAPA[8:106])
IPIPkeys <- map(IPIPkeysList, function(x) {
    x[match(usedQ, x)]
    na.omit(x)
})
# select only IPIP 100
IPIPkeys <- IPIPkeys[1:4]

```

```{r demographics}
# idk if this is what we want here - tableby package not available
map((SAPA[c(2,3,5,6,7)]), table)

```

```{r individual subject scores}
# score items
scores <- psych::scoreItems(keys = IPIPkeys, items = SAPA, min=1, max=6, totals = FALSE, impute = 'none')$scores


```

```{r #3 descriptives statistics}

```

```{r #4 average scores by factor}

```

```{r #5 factor structure}

```

```{r #6/7 state-wise descriptives}
# combine demographics & traits
factorSAPA <- cbind(SAPA[1:7], scores)

# nest data by state
by_state <- split(factorSAPA, factorSAPA$state)

# descriptive stats - THERE SHOULD BE A BETTER WAY TO DO THIS (SOME KIND OF NESTED MAP FXN?)  ## summarize_at?
stateAgree <- map(by_state, ~summarize(.x, meanFactor = mean(IPIP100agreeableness, na.rm = TRUE),
                                    sdFactor = sd(IPIP100agreeableness, na.rm = TRUE),
                                    nFactor = length(IPIP100agreeableness)))
stateCons <- map(by_state, ~summarize(.x, meanFactor = mean(IPIP100conscientiousness, na.rm = TRUE),
                                    sdFactor = sd(IPIP100conscientiousness, na.rm = TRUE),
                                    nFactor = length(IPIP100conscientiousness)))
stateExtra <- map(by_state, ~summarize(.x, meanFactor = mean(IPIP100extraversion, na.rm = TRUE),
                                    sdFactor = sd(IPIP100extraversion, na.rm = TRUE),
                                    nFactor = length(IPIP100extraversion)))
stateIntel <- map(by_state, ~summarize(.x, meanFactor = mean(IPIP100intellect, na.rm = TRUE),
                                    sdFactor = sd(IPIP100intellect, na.rm = TRUE),
                                    nFactor = length(IPIP100intellect)))
# group all factors in list
allFactor = list(stateAgree, stateCons, stateExtra, stateIntel)
names(allFactor) = c('Agreeableness', 'Conscientiousness', 'Extraversion', 'Intellect')

# function to create table - SHOULD FIND A WAY TO CAPTION EACH TABLE BY STATE & FACTOR
makeTable <- function(x) {
  kable(x, booktabs = TRUE, longtable = TRUE, col.names = c("Mean", "SD", "N"), 
        caption = paste('State of ', x, ' Descriptives')) %>% 
    landscape() %>% 
    kable_styling(font_size = 12, latex_options = c("scale_down", "repeat_header")) %>% 
    kable_classic() 
}

# create tables for each factor & state
map(allFactor, ~map(.x, ~makeTable(.x)))

```

```{r #8 average scores by factor - from nested states}


```

```{r #9 factor structure - from nested states}
by_stateFactors <- split(SAPA, factorSAPA$state)

stateFactor <- map(by_stateFactors, ~fa.parallel(cov(.x[,8:106], use = "pairwise.complete.obs"), n.iter = 20, cor = "cov")$nfact)

```

\renewcommand{\thetable}{S\arabic{table}} 
\renewcommand{\thefigure}{S\arabic{figure}}



\definecolor{fancyTextColor}{HTML}{4284f5}
\definecolor{hightlightColor}{HTML}{FFFF66}

\newpage

\listoftables

\newpage

\listoffigures

\newpage



